from mcp.server.fastmcp import FastMCP
from openai import OpenAI
import base64

# Initialize FastMCP server
mcp = FastMCP("LM Studio VLM Server")

# Initialize OpenAI client pointing to LM Studio
client = OpenAI(base_url="http://localhost:8000/v1", api_key="lm-studio")

def query_vlm(image_path, prompt):
    """Encodes image and sends request to LM Studio API."""
    with open(image_path, "rb") as image_file:
        base64_image = base64.b64encode(image_file.read()).decode('utf-8')

    response = client.chat.completions.create(
        model="qwen/qwen3-vl-4b", # LM Studio usually ignores this and uses the loaded model
        messages=[
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {
                        "type": "image_url",
                        "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"},
                    },
                ],
            }
        ],
        max_tokens=500,
    )
    return response.choices[0].message.content

@mcp.tool()
def describe(image_path: str) -> str:
    """Detailed caption for the image."""
    return query_vlm(image_path, "Describe this image in detail.")

@mcp.tool()
def detect_person(image_path: str) -> str:
    """Identify people in the image."""
    return query_vlm(image_path, "List all people in this image and their activities.")

@mcp.tool()
def ocr(image_path: str) -> str:
    """Extract all text from the image."""
    return query_vlm(image_path, "Transcribe all text from this image.")

@mcp.tool()
def format_query(keyword: str, image_path: str) -> dict:
    """
    Takes a keyword and formats it into a nice query using the VLM model itself.
    Then analyzes the image using the formatted query.
    
    Args:
        keyword: A simple keyword (e.g., "sun", "people", "text")
        image_path: Path to the image file
    
    Returns:
        A dict with:
        - formatted_query: The enhanced query generated by the VLM
        - analysis: The image analysis result using the formatted query
    """
    # First, use the model to enhance the keyword into a better query
    enhancement_prompt = f"""You are a prompt engineering expert. A user provided the keyword: "{keyword}"
    
Convert this keyword into a detailed, specific image analysis query that will help analyze images better.
The query should be comprehensive, asking for detailed observations from interesting perspectives.

Return ONLY the formatted query, nothing else. No quotes, no explanation."""
    
    formatted_query = query_vlm(image_path, enhancement_prompt)
    
    # Now use the formatted query to analyze the image
    analysis = query_vlm(image_path, formatted_query)
    
    return {
        "keyword": keyword,
        "formatted_query": formatted_query,
        "analysis": analysis
    }


@mcp.tool()
def present_checker(keyword: str, image_path: str) -> bool:
    """Check if the keyword concept is present in the image."""
    # First we enhance the keyword into a better query to check presence leads to binary answer
    enhancement_prompt = f"""You are a prompt engineering expert. A user provided the keyword: "{keyword}" 
    Convert this keyword into a precise question that can be answered with 'Yes' or 'No' regarding the presence of this concept in an image.
    Return ONLY the question, nothing else. No quotes, no explanation."""

    modified_prompt = query_vlm(image_path, enhancement_prompt)

    # Now ask the modified prompt to check presence     
    response = query_vlm(image_path, modified_prompt)
    return {
        "keyword": keyword,
        "modified_prompt": modified_prompt,
        "response": response,
        "present": response.strip().lower() in ["yes", "true", "1"]
    }

if __name__ == "__main__":
    mcp.run()
